In [ ]:
import requests
import pandas as pd

# Define your Alpha Vantage API key
api_key = 'A5K2F1KTMVFXWP13'

# Define the symbol for the stock
symbol = 'FDX'

# Define the base URL for Alpha Vantage
base_url = 'https://www.alphavantage.co/query'

# Function to fetch financial data
def fetch_data(function, symbol, api_key):
    params = {
        'function': function,
        'symbol': symbol,
        'apikey': api_key
    }
    response = requests.get(base_url, params=params)
    data = response.json()
    return data

In [ ]:
# Fetch income statements (yearly and quarterly)
income_yearly = fetch_data('INCOME_STATEMENT', symbol, api_key)['annualReports']
income_quarterly = fetch_data('INCOME_STATEMENT', symbol, api_key)['quarterlyReports']

# Fetch balance sheets (yearly and quarterly)
balance_yearly = fetch_data('BALANCE_SHEET', symbol, api_key)['annualReports']
balance_quarterly = fetch_data('BALANCE_SHEET', symbol, api_key)['quarterlyReports']

# Fetch cash flow statements (yearly and quarterly)
cash_flow_yearly = fetch_data('CASH_FLOW', symbol, api_key)['annualReports']
cash_flow_quarterly = fetch_data('CASH_FLOW', symbol, api_key)['quarterlyReports']

# Convert the data to pandas DataFrames
df_income_yearly = pd.DataFrame(income_yearly)
df_income_quarterly = pd.DataFrame(income_quarterly)

df_balance_yearly = pd.DataFrame(balance_yearly)
df_balance_quarterly = pd.DataFrame(balance_quarterly)

df_cash_flow_yearly = pd.DataFrame(cash_flow_yearly)
df_cash_flow_quarterly = pd.DataFrame(cash_flow_quarterly)

# Display the dataframes
print(df_income_yearly.head())
print(df_income_quarterly.head())
print(df_balance_yearly.head())
print(df_balance_quarterly.head())
print(df_cash_flow_yearly.head())
print(df_cash_flow_quarterly.head())

In [38]:
df_income_yearly

,fiscalDateEnding,reportedCurrency,grossProfit,totalRevenue,costOfRevenue,costofGoodsAndServicesSold,operatingIncome,sellingGeneralAndAdministrative,researchAndDevelopment,operatingExpenses,...,depreciation,depreciationAndAmortization,incomeBeforeTax,incomeTaxExpense,interestAndDebtExpense,netIncomeFromContinuingOperations,comprehensiveIncomeNetOfTax,ebit,ebitda,netIncome
0,2024,USD,47890000000,86948000000,39058000000,8001000000,5559000000,584000000,None,13893000000,...,None,77000000,5836000000,1505000000,745000000,4331000000,4299000000,6581000000,6658000000,4331000000
1,2023,USD,49408000000,89461000000,40053000000,9266000000,4912000000,617000000,None,15346000000,...,None,88000000,5363000000,1391000000,694000000,3972000000,3748000000,6057000000,6145000000,3972000000
2,2022,USD,50814000000,92823000000,42009000000,8487000000,6245000000,660000000,None,14785000000,...,None,78000000,4896000000,1070000000,689000000,3826000000,3455000000,5585000000,5663000000,3826000000
3,2021,USD,47463000000,82773000000,35310000000,6210000000,5857000000,628000000,None,13503000000,...,None,72000000,6674000000,1443000000,1186000000,5231000000,5646000000,7467000000,7539000000,5231000000
4,2020,USD,35959000000,68545000000,32586000000,6049000000,2417000000,595000000,None,12353000000,...,None,84000000,1669000000,383000000,672000000,1286000000,953000000,2341000000,2425000000,1286000000
5,2019,USD,20223000000,69113000000,48890000000,16654000000,4466000000,3739000000,None,14537000000,...,None,82000000,655000000,115000000,588000000,540000000,253000000,1243000000,1325000000,540000000
6,2018,USD,17130000000,65450000000,48320000000,15101000000,4272000000,26756000000,None,36834000000,...,None,87000000,4353000000,-219000000,558000000,4572000000,4409000000,4911000000,4998000000,4572000000
7,2017,USD,13555000000,60319000000,46764000000,13630000000,4566000000,24992000000,None,36897000000,...,2900000000,2995000000,4579000000,1582000000,512000000,2997000000,2751000000,5091000000,8086000000,2997000000
8,2016,USD,11399000000,50365000000,38966000000,14473000000,3077000000,21862000000,None,47288000000,...,2600000000,2631000000,2740000000,920000000,336000000,1820000000,1479000000,3076000000,5707000000,1820000000
9,2015,USD,18791000000,47453000000,28662000000,5819000000,1867000000,19956000000,None,45586000000,...,2600000000,2611000000,1627000000,577000000,235000000,1050000000,716000000,1862000000,4473000000,1050000000
10,2014,USD,17248000000,45567000000,28319000000,6419000000,3815000000,19313000000,None,41752000000,...,2600000000,2587000000,3658000000,1334000000,160000000,2097000000,2223000000,3818000000,6405000000,2324000000
11,2013,USD,18258000000,44287000000,26029000000,6655000000,4434000000,19247000000,None,39853000000,...,2300000000,2386000000,4338000000,1622000000,82000000,1561000000,2694000000,4420000000,6806000000,2716000000
12,2012,USD,16862000000,42680000000,25818000000,6936000000,3186000000,18748000000,None,39494000000,...,2100000000,2113000000,3141000000,1109000000,-52000000,2032000000,-371000000,3193000000,5306000000,2032000000
13,2011,USD,15216000000,39304000000,24088000000,6130000000,2378000000,17869000000,None,36926000000,...,1900000000,32000000,2265000000,813000000,-86000000,1452000000,1342000000,2351000000,2383000000,1452000000
14,2010,USD,13910000000,34734000000,20824000000,4821000000,1998000000,14027000000,None,46966000000,...,1900000000,1958000000,1894000000,710000000,79000000,1184000000,117000000,1815000000,3773000000,1184000000

In [ ]:
# Convert 'fiscalDateEnding' to year format for all yearly DataFrames
for df in [df_income_yearly, df_balance_yearly, df_cash_flow_yearly]:
    df['fiscalDateEnding'] = pd.to_datetime(df['fiscalDateEnding']).dt.year

# Convert 'fiscalDateEnding' to quarter format for all quarterly DataFrames
for df in [df_income_quarterly, df_balance_quarterly, df_cash_flow_quarterly]:
    df['fiscalDateEnding'] = pd.to_datetime(df['fiscalDateEnding'])
    df['fiscalDateEnding'] = df['fiscalDateEnding'].dt.to_period('Q').astype(str)

In [ ]:

# Column mappings for renaming
income_column_mapping = {
    'totalRevenue': 'Total Revenue',
    'costOfRevenue': 'Cost of Revenue',
    'grossProfit': 'Gross Profit',
    'costofGoodsAndServicesSold': 'Cost of Goods and Services Sold',
    'operatingIncome': 'Operating Income',
    'sellingGeneralAndAdministrative': 'Selling, General, and Administrative Expenses',
    'researchAndDevelopment': 'Research and Development',
    'operatingExpenses': 'Operating Expenses',
    'investmentIncomeNet': 'Net Investment Income',
    'netInterestIncome': 'Net Interest Income',
    'interestIncome': 'Interest Income',
    'interestExpense': 'Interest Expense',
    'nonInterestIncome': 'Non-Interest Income',
    'otherNonOperatingIncome': 'Other Non-Operating Income',
    'depreciation': 'Depreciation',
    'depreciationAndAmortization': 'Depreciation and Amortization',
    'incomeBeforeTax': 'Income Before Tax',
    'incomeTaxExpense': 'Income Tax Expense',
    'interestAndDebtExpense': 'Interest and Debt Expense',
    'netIncomeFromContinuingOperations': 'Net Income From Continuing Operations',
    'comprehensiveIncomeNetOfTax': 'Comprehensive Income Net of Tax',
    'ebit': 'EBIT',
    'ebitda': 'EBITDA',
    'netIncome': 'Net Income'
}

balance_column_mapping = {
    'totalCurrentAssets': 'Total Current Assets',
    'cashAndCashEquivalentsAtCarryingValue': 'Cash and Cash Equivalents',
    'cashAndShortTermInvestments': 'Cash and Short Term Investments',
    'inventory': 'Inventory',
    'currentNetReceivables': 'Current Net Receivables',
    'totalNonCurrentAssets': 'Total Non-Current Assets',
    'propertyPlantEquipment': 'Property, Plant, and Equipment',
    'accumulatedDepreciationAmortizationPPE': 'Accumulated Depreciation and Amortization (PPE)',
    'intangibleAssets': 'Intangible Assets',
    'goodwill': 'Goodwill',
    'longTermInvestments': 'Long-Term Investments',
    'otherCurrentAssets': 'Other Current Assets',
    'otherNonCurrentAssets': 'Other Non-Current Assets',
    'totalAssets': 'Total Assets',
    'totalCurrentLiabilities': 'Total Current Liabilities',
    'currentAccountsPayable': 'Current Accounts Payable',
    'deferredRevenue': 'Deferred Revenue',
    'currentDebt': 'Current Debt',
    'shortTermDebt': 'Short-Term Debt',
    'totalNonCurrentLiabilities': 'Total Non-Current Liabilities',
    'longTermDebt': 'Long-Term Debt',
    'otherCurrentLiabilities': 'Other Current Liabilities',
    'otherNonCurrentLiabilities': 'Other Non-Current Liabilities',
    'totalLiabilities': 'Total Liabilities',
    'totalShareholderEquity': 'Total Shareholder Equity',
    'treasuryStock': 'Treasury Stock',
    'retainedEarnings': 'Retained Earnings',
    'commonStock': 'Common Stock',
    'commonStockSharesOutstanding': 'Common Stock Shares Outstanding'
}

cashflow_column_mapping = {
    'operatingCashflow': 'Operating Cash Flow',
    'paymentsForOperatingActivities': 'Payments for Operating Activities',
    'proceedsFromOperatingActivities': 'Proceeds from Operating Activities',
    'changeInOperatingLiabilities': 'Change in Operating Liabilities',
    'changeInOperatingAssets': 'Change in Operating Assets',
    'depreciationDepletionAndAmortization': 'Depreciation, Depletion, and Amortization',
    'capitalExpenditures': 'Capital Expenditures',
    'changeInReceivables': 'Change in Receivables',
    'changeInInventory': 'Change in Inventory',
    'profitLoss': 'Profit/Loss',
    'cashflowFromInvestment': 'Cash Flow from Investment',
    'cashflowFromFinancing': 'Cash Flow from Financing',
    'proceedsFromRepaymentsOfShortTermDebt': 'Proceeds from Repayments of Short-Term Debt',
    'paymentsForRepurchaseOfCommonStock': 'Payments for Repurchase of Common Stock',
    'paymentsForRepurchaseOfEquity': 'Payments for Repurchase of Equity',
    'paymentsForRepurchaseOfPreferredStock': 'Payments for Repurchase of Preferred Stock',
    'dividendPayout': 'Dividend Payout',
    'dividendPayoutCommonStock': 'Dividend Payout (Common Stock)',
    'dividendPayoutPreferredStock': 'Dividend Payout (Preferred Stock)',
    'proceedsFromIssuanceOfCommonStock': 'Proceeds from Issuance of Common Stock',
    'proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet': 'Proceeds from Issuance of Long-Term Debt and Capital Securities (Net)',
    'proceedsFromIssuanceOfPreferredStock': 'Proceeds from Issuance of Preferred Stock',
    'proceedsFromRepurchaseOfEquity': 'Proceeds from Repurchase of Equity',
    'proceedsFromSaleOfTreasuryStock': 'Proceeds from Sale of Treasury Stock',
    'changeInCashAndCashEquivalents': 'Change in Cash and Cash Equivalents',
    'changeInExchangeRate': 'Change in Exchange Rate',
    'netIncome': 'Net Income'
}

# Function to rename, reorder, and transpose
def rename_reorder_transpose(df, column_mapping, column_order):
    # Rename columns
    df = df.rename(columns=column_mapping)
    
    # Reorder columns
    df = df[['fiscalDateEnding'] + column_order]
    
    # Transpose the DataFrame
    df_transposed = df.set_index('fiscalDateEnding').transpose()
    
    return df_transposed

# Column order for the Income Statement
income_column_order = [
    'Total Revenue',
    'Cost of Revenue',
    'Gross Profit',
    'Selling, General, and Administrative Expenses',
    'Research and Development',
    'Operating Expenses',
    'Operating Income',
    'Net Investment Income',
    'Net Interest Income',
    'Interest Income',
    'Interest Expense',
    'Non-Interest Income',
    'Other Non-Operating Income',
    'Depreciation',
    'Depreciation and Amortization',
    'Income Before Tax',
    'Income Tax Expense',
    'Interest and Debt Expense',
    'Net Income From Continuing Operations',
    'Comprehensive Income Net of Tax',
    'EBIT',
    'EBITDA',
    'Net Income'
]

# Column order for the Balance Sheet
balance_column_order = [
    'Total Current Assets',
    'Cash and Cash Equivalents',
    'Cash and Short Term Investments',
    'Inventory',
    'Current Net Receivables',
    'Total Non-Current Assets',
    'Property, Plant, and Equipment',
    'Accumulated Depreciation and Amortization (PPE)',
    'Intangible Assets',
    'Goodwill',
    'Long-Term Investments',
    'Other Current Assets',
    'Other Non-Current Assets',
    'Total Assets',
    'Total Current Liabilities',
    'Current Accounts Payable',
    'Deferred Revenue',
    'Current Debt',
    'Short-Term Debt',
    'Total Non-Current Liabilities',
    'Long-Term Debt',
    'Other Current Liabilities',
    'Other Non-Current Liabilities',
    'Total Liabilities',
    'Total Shareholder Equity',
    'Treasury Stock',
    'Retained Earnings',
    'Common Stock',
    'Common Stock Shares Outstanding'
]

# Column order for the Cash Flow Statement
cashflow_column_order = [
    'Operating Cash Flow',
    'Payments for Operating Activities',
    'Proceeds from Operating Activities',
    'Change in Operating Liabilities',
    'Change in Operating Assets',
    'Depreciation, Depletion, and Amortization',
    'Change in Receivables',
    'Change in Inventory',
    'Profit/Loss',
    'Cash Flow from Investment',
    'Capital Expenditures',
    'Cash Flow from Financing',
    'Proceeds from Repayments of Short-Term Debt',
    'Payments for Repurchase of Common Stock',
    'Payments for Repurchase of Equity',
    'Payments for Repurchase of Preferred Stock',
    'Dividend Payout',
    'Dividend Payout (Common Stock)',
    'Dividend Payout (Preferred Stock)',
    'Proceeds from Issuance of Common Stock',
    'Proceeds from Issuance of Long-Term Debt and Capital Securities (Net)',
    'Proceeds from Issuance of Preferred Stock',
    'Proceeds from Repurchase of Equity',
    'Proceeds from Sale of Treasury Stock',
    'Change in Cash and Cash Equivalents',
    'Change in Exchange Rate',
    'Net Income'
]

# Example usage: rename, reorder, and transpose all the statements
df_income_yearly_transposed = rename_reorder_transpose(df_income_yearly, income_column_mapping, income_column_order)
df_income_quarterly_transposed = rename_reorder_transpose(df_income_quarterly, income_column_mapping, income_column_order)

df_balance_yearly_transposed = rename_reorder_transpose(df_balance_yearly, balance_column_mapping, balance_column_order)
df_balance_quarterly_transposed = rename_reorder_transpose(df_balance_quarterly, balance_column_mapping, balance_column_order)

df_cash_flow_yearly_transposed = rename_reorder_transpose(df_cash_flow_yearly, cashflow_column_mapping, cashflow_column_order)
df_cash_flow_quarterly_transposed = rename_reorder_transpose(df_cash_flow_quarterly, cashflow_column_mapping, cashflow_column_order)

# Display the transposed DataFrames
print("Income Yearly Transposed:")
print(df_income_yearly_transposed.head())

print("\nBalance Sheet Yearly Transposed:")
print(df_balance_yearly_transposed.head())

print("\nCash Flow Yearly Transposed:")
print(df_cash_flow_yearly_transposed.head())

In [ ]:
def clean_and_convert_to_numeric(df):
    # Convert all columns except the index to numeric, replacing non-numeric entries (e.g., None) with 0
    df = df.apply(pd.to_numeric, errors='coerce').fillna(0)
    return df

In [ ]:
# Clean and convert data for each transposed DataFrame
df_income_yearly_transposed = clean_and_convert_to_numeric(df_income_yearly_transposed)
df_income_quarterly_transposed = clean_and_convert_to_numeric(df_income_quarterly_transposed)
df_balance_yearly_transposed = clean_and_convert_to_numeric(df_balance_yearly_transposed)
df_balance_quarterly_transposed = clean_and_convert_to_numeric(df_balance_quarterly_transposed)
df_cash_flow_yearly_transposed = clean_and_convert_to_numeric(df_cash_flow_yearly_transposed)
df_cash_flow_quarterly_transposed = clean_and_convert_to_numeric(df_cash_flow_quarterly_transposed)

In [ ]:
output_file = "fdx_financial_statements_API.xlsx"

with pd.ExcelWriter(output_file, engine='xlsxwriter') as writer:
    # Write each DataFrame to a separate sheet
    df_income_yearly_transposed.to_excel(writer, sheet_name='Income Yearly')
    df_income_quarterly_transposed.to_excel(writer, sheet_name='Income Quarterly')
    df_balance_yearly_transposed.to_excel(writer, sheet_name='Balance Sheet Yearly')
    df_balance_quarterly_transposed.to_excel(writer, sheet_name='Balance Sheet Quarterly')
    df_cash_flow_yearly_transposed.to_excel(writer, sheet_name='Cash Flow Yearly')
    df_cash_flow_quarterly_transposed.to_excel(writer, sheet_name='Cash Flow Quarterly')

In [ ]:
# Extract necessary values from the DataFrame
total_revenue = df_income_yearly_transposed.loc['Total Revenue', '2024']
cost_of_revenue = df_income_yearly_transposed.loc['Cost of Revenue', '2024']
selling_admin_expenses = df_income_yearly_transposed.loc['Selling, General, and Administrative Expenses', '2024']
r_and_d_expenses = df_income_yearly_transposed.loc['Research and Development', '2024']
operating_expenses = df_income_yearly_transposed.loc['Operating Expenses', '2024']
net_investment_income = df_income_yearly_transposed.loc['Net Investment Income', '2024']
net_interest_income = df_income_yearly_transposed.loc['Net Interest Income', '2024']
other_non_operating_income = df_income_yearly_transposed.loc['Other Non-Operating Income', '2024']
depreciation_amortization = df_income_yearly_transposed.loc['Depreciation and Amortization', '2024']
income_tax_expense = df_income_yearly_transposed.loc['Income Tax Expense', '2024']
net_income = df_income_yearly_transposed.loc['Net Income', '2024']  # Net income remains unchanged

# 1. Calculate Gross Profit
df_income_yearly_transposed.loc['Gross Profit', '2024'] = total_revenue - cost_of_revenue

# 2. Calculate Operating Income
df_income_yearly_transposed.loc['Operating Income', '2024'] = (
    df_income_yearly_transposed.loc['Gross Profit', '2024'] 
    - selling_admin_expenses 
    - r_and_d_expenses 
    - operating_expenses
)

# 3. Calculate Income Before Tax
df_income_yearly_transposed.loc['Income Before Tax', '2024'] = (
    df_income_yearly_transposed.loc['Operating Income', '2024']
    + net_investment_income 
    + net_interest_income 
    + other_non_operating_income
)

# 4. Ensure Income Before Tax and Income Tax Expense reconcile to Net Income
# We assume the relationship: Net Income = Income Before Tax - Income Tax Expense
df_income_yearly_transposed.loc['Income Before Tax', '2024'] = net_income + income_tax_expense

# Save the corrected data to Excel
output_file = "corrected_financial_statements_fixed_net_income.xlsx"

with pd.ExcelWriter(output_file, engine='xlsxwriter') as writer:
    # Write the DataFrame to the Excel file
    df_income_yearly_transposed.to_excel(writer, sheet_name='Income Yearly Corrected')